/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.igu;

import com.logic.Book;
import java.awt.*;
import java.util.ArrayList;


/**
 *
 * @author eljot
 */
public class BookLoan extends javax.swing.JFrame {
    
    private ArrayList<Book> bibliotec = new ArrayList<>();
    private ArrayList<Book> bibliotecLoan = new ArrayList<>();
    private final Home parentHome;
    
    

    public BookLoan(Home parentHome) {
        initComponents();   
        this.parentHome = parentHome;
        this.bibliotec = parentHome.bibliotec;
        this.bibliotecLoan = parentHome.bibliotecLoan;
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPbackground = new javax.swing.JPanel();
        JLmenu = new javax.swing.JPanel();
        JLiconBuho = new javax.swing.JLabel();
        JPoptions = new javax.swing.JPanel();
        JPoptions_books = new javax.swing.JPanel();
        JLloans = new javax.swing.JLabel();
        JLreturn_book = new javax.swing.JLabel();
        JLreturn = new javax.swing.JLabel();
        JPicon = new javax.swing.JPanel();
        JLicon_buho = new javax.swing.JLabel();
        JLtitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLmenu.setBackground(new java.awt.Color(51, 51, 51));

        JLiconBuho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Buho-creado-luna.png"))); // NOI18N

        JPoptions.setBackground(new java.awt.Color(51, 51, 51));
        JPoptions.setForeground(new java.awt.Color(102, 102, 102));

        JPoptions_books.setBackground(new java.awt.Color(102, 102, 102));

        JLloans.setBackground(new java.awt.Color(51, 51, 51));
        JLloans.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        JLloans.setForeground(new java.awt.Color(255, 255, 255));
        JLloans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLloans.setText("Book loans");
        JLloans.setOpaque(true);
        JLloans.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JLloansMouseMoved(evt);
            }
        });
        JLloans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLloansMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLloansMouseExited(evt);
            }
        });

        JLreturn_book.setBackground(new java.awt.Color(51, 51, 51));
        JLreturn_book.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        JLreturn_book.setForeground(new java.awt.Color(255, 255, 255));
        JLreturn_book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLreturn_book.setText("Return of books");
        JLreturn_book.setOpaque(true);
        JLreturn_book.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JLreturn_bookMouseMoved(evt);
            }
        });
        JLreturn_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLreturn_bookMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLreturn_bookMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JPoptions_booksLayout = new javax.swing.GroupLayout(JPoptions_books);
        JPoptions_books.setLayout(JPoptions_booksLayout);
        JPoptions_booksLayout.setHorizontalGroup(
            JPoptions_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLloans, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(JLreturn_book, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        JPoptions_booksLayout.setVerticalGroup(
            JPoptions_booksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPoptions_booksLayout.createSequentialGroup()
                .addComponent(JLloans, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JLreturn_book, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JLreturn.setBackground(new java.awt.Color(51, 51, 51));
        JLreturn.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        JLreturn.setForeground(new java.awt.Color(255, 255, 255));
        JLreturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLreturn.setText("Return ");
        JLreturn.setOpaque(true);
        JLreturn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JLreturnMouseMoved(evt);
            }
        });
        JLreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLreturnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLreturnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JPoptionsLayout = new javax.swing.GroupLayout(JPoptions);
        JPoptions.setLayout(JPoptionsLayout);
        JPoptionsLayout.setHorizontalGroup(
            JPoptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPoptionsLayout.createSequentialGroup()
                .addGroup(JPoptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLreturn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPoptions_books, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPoptionsLayout.setVerticalGroup(
            JPoptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPoptionsLayout.createSequentialGroup()
                .addComponent(JPoptions_books, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251)
                .addComponent(JLreturn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JLmenuLayout = new javax.swing.GroupLayout(JLmenu);
        JLmenu.setLayout(JLmenuLayout);
        JLmenuLayout.setHorizontalGroup(
            JLmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPoptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JLmenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(JLiconBuho)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JLmenuLayout.setVerticalGroup(
            JLmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JLmenuLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(JLiconBuho)
                .addGap(35, 35, 35)
                .addComponent(JPoptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPbackground.add(JLmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 600));

        JPicon.setBackground(new java.awt.Color(0, 0, 0));

        JLicon_buho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Buho-creado-luna.png"))); // NOI18N

        JLtitle.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        JLtitle.setForeground(new java.awt.Color(255, 255, 255));
        JLtitle.setText("Owl Library");

        javax.swing.GroupLayout JPiconLayout = new javax.swing.GroupLayout(JPicon);
        JPicon.setLayout(JPiconLayout);
        JPiconLayout.setHorizontalGroup(
            JPiconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPiconLayout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addGroup(JPiconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPiconLayout.createSequentialGroup()
                        .addComponent(JLtitle)
                        .addGap(302, 302, 302))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPiconLayout.createSequentialGroup()
                        .addComponent(JLicon_buho)
                        .addGap(333, 333, 333))))
        );
        JPiconLayout.setVerticalGroup(
            JPiconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPiconLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(JLicon_buho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLtitle)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        JPbackground.add(JPicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 810, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setListbook(ArrayList books){
        this.bibliotec = books;
    }
    public ArrayList<Book> getListbook(){
        return bibliotec;
    }
    public void setListbookLoan(ArrayList books){
        this.bibliotecLoan = books;
    }
    
    public ArrayList<Book> getBibliotecLoan() {
    return bibliotecLoan;
}
 

    private void JLloansMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLloansMouseMoved
        // TODO add your handling code here:
        JLloans.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_JLloansMouseMoved

    private void JLloansMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLloansMouseExited
        // TODO add your handling code here:
        JLloans.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_JLloansMouseExited

    private void JLreturn_bookMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLreturn_bookMouseMoved
        // TODO add your handling code here:
        JLreturn_book.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_JLreturn_bookMouseMoved

    private void JLreturn_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLreturn_bookMouseExited
        // TODO add your handling code here:
        JLreturn_book.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_JLreturn_bookMouseExited

    private void JLreturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLreturnMouseExited
        // TODO add your handling code here:
         JLreturn.setBackground(new java.awt.Color(51,51,51));
    }//GEN-LAST:event_JLreturnMouseExited

    private void JLreturnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLreturnMouseMoved
        // TODO add your handling code here:
        JLreturn.setBackground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_JLreturnMouseMoved

    private void JLloansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLloansMouseClicked
        // TODO add your handling code here:
        BookLoanPageLoan page1 = new BookLoanPageLoan(this);
        page1.setListbook(bibliotec);

        page1.setSize(810,600);
        page1.setLocation(0,0);

        JPicon.removeAll();
        JPicon.add(page1, BorderLayout.CENTER);
        JPicon.revalidate();
        JPicon.repaint();
    }//GEN-LAST:event_JLloansMouseClicked

    private void JLreturn_bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLreturn_bookMouseClicked
        // TODO add your handling code here:
        BookLoanPageReturn page2 = new BookLoanPageReturn(this);
        page2.xd(bibliotecLoan);
        page2.setSize(810,600);
        page2.setLocation(0,0);

        JPicon.removeAll();
        JPicon.add(page2, BorderLayout.CENTER);
        JPicon.revalidate();
        JPicon.repaint();
    }//GEN-LAST:event_JLreturn_bookMouseClicked

    private void JLreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLreturnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        parentHome.setVisible(true);
        parentHome.setListbook(bibliotec);
        parentHome.setListbookLoan(bibliotecLoan);
    }//GEN-LAST:event_JLreturnMouseClicked




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLiconBuho;
    private javax.swing.JLabel JLicon_buho;
    private javax.swing.JLabel JLloans;
    private javax.swing.JPanel JLmenu;
    private javax.swing.JLabel JLreturn;
    private javax.swing.JLabel JLreturn_book;
    private javax.swing.JLabel JLtitle;
    private javax.swing.JPanel JPbackground;
    private javax.swing.JPanel JPicon;
    private javax.swing.JPanel JPoptions;
    private javax.swing.JPanel JPoptions_books;
    // End of variables declaration//GEN-END:variables
}
