/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.igu;
import com.logic.Book;
import com.logic.PhysicalBook;
import com.logic.DigitalBook;
import com.logic.Bookcontroller;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.awt.*;

import java.util.ArrayList;
/**
 *
 * @author USUARIO
 */
public class BookCrud extends javax.swing.JFrame {
   public ArrayList<Book>bibliotec = new ArrayList<Book>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookCrud.class.getName());
    /**
     * Creates new form BookCrud
     */
    Bookcontroller controller = new Bookcontroller ();
    private final BookTableModel tableModel = new BookTableModel();
    private final Home parentHome;
    public BookCrud(Home parentHome) {
        initComponents();
        this.parentHome = parentHome;
        JOptionPane.showMessageDialog(null, bibliotec.get(1).csvDescriptionProduct());
    }
public void setbooks(ArrayList Book){
    this.bibliotec = Book;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("regresar a inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 120, 30));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 80, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 960, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        parentHome.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        try {
            String name = JOptionPane.showInputDialog(this, "Name:");
            if (name == null || name.trim().isEmpty()) return; // usuario canceló o vacío
            String author = JOptionPane.showInputDialog(this, "Author:"); if (author == null) author = "";
            String year = JOptionPane.showInputDialog(this, "Year:"); if (year == null) year = "";
            String synopsis = JOptionPane.showInputDialog(this, "Synopsis:"); if (synopsis == null) synopsis = "";
            String[] types = new String[]{"physical","digital"};
            Object sel = JOptionPane.showInputDialog(this, "Type:", "Type", JOptionPane.QUESTION_MESSAGE, null, types, types[0]);
            if (sel == null) return; String type = sel.toString();
            int dispo = JOptionPane.showConfirmDialog(this, "Available?", "Availability", JOptionPane.YES_NO_OPTION);
            boolean available = dispo == JOptionPane.YES_OPTION;

            // Crear la entidad Book apropiada y delegar en el controlador.
            Book b = "physical".equalsIgnoreCase(type)
                    ? new PhysicalBook(0, name, author, year, synopsis, available, "physical")
                    : new DigitalBook(0, name, author, year, synopsis, available, "digital");
            controller.add(b);
            // Refrescar la tabla mostrando la lista actualizada desde el controlador.
            tableModel.setData(controller.list());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error adding book: "+ex.getMessage());
        }
    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
