/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.igu;

import com.logic.Book;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eljot
 */
public class BookLoanPageReturn extends javax.swing.JPanel {

    /**
     * Creates new form BookLoanPageReturn
     */
    private DefaultTableModel tableColumnModel;
    ArrayList<Book> bookloans = new ArrayList<>();
    ArrayList<Book> bibliotec = new ArrayList<>();
    private BookLoan parentFrame;
    
    public BookLoanPageReturn(BookLoan parentFrame) {
        initComponents();
        this.parentFrame = parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     */
    


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 700, 290));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 200, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(null, "selecionaD", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        String StringBook = String.valueOf(tableColumnModel.getValueAt(row, 0));
        int idBook = Integer.parseInt(StringBook);
        for (Book book : parentFrame.getListbook()){
            if(idBook == book.getId()){
                book.setDisposability(true);
                parentFrame.getBibliotecLoan().remove(book);
                tableColumnModel.removeRow(row);
                JOptionPane.showMessageDialog(null, "se delvovio el libro :D", "Información", JOptionPane.INFORMATION_MESSAGE);
                break;
            }
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    public void xd(ArrayList books){
        this.bookloans = books;
        mostTable();
    }

    private void mostTable(){
        tableColumnModel = new DefaultTableModel();

        tableColumnModel.addColumn("Id");
        tableColumnModel.addColumn("Name");
        tableColumnModel.addColumn("Author name");
        tableColumnModel.addColumn("Year");
        tableColumnModel.addColumn("Type");
        tableColumnModel.addColumn("Synopsis");
        tableColumnModel.addColumn("Disposability");

        this.jTable1.setModel(tableColumnModel);
    
        String [] date = new String[7];
        for(Book book : bookloans){
                date [0] = String.valueOf(book.getId());
                date [1] = book.getName();
                date [2] = book.getAuthorname();
                date [3] = book.getYear();
                date [4] = book.getType();
                date [5] = book.getSynopsis();
                date [6] = String.valueOf(book.isDisposability());
                tableColumnModel.addRow(date);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
