/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.igu;

/**
 *
 * @author eljot
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Buho = new javax.swing.JLabel();
        buho_background = new javax.swing.JPanel();
        options_background = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        traspareted_background = new javax.swing.JPanel();
        background_bibliotec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(204, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Buho-creado-luna.png"))); // NOI18N
        background.add(Buho, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        buho_background.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout buho_backgroundLayout = new javax.swing.GroupLayout(buho_background);
        buho_background.setLayout(buho_backgroundLayout);
        buho_backgroundLayout.setHorizontalGroup(
            buho_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        buho_backgroundLayout.setVerticalGroup(
            buho_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        background.add(buho_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        options_background.setBackground(new java.awt.Color(51, 51, 51));

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        jButton7.setText("jButton7");

        jButton8.setText("jButton8");

        title.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Biblioteca del Buho");

        javax.swing.GroupLayout options_backgroundLayout = new javax.swing.GroupLayout(options_background);
        options_background.setLayout(options_backgroundLayout);
        options_backgroundLayout.setHorizontalGroup(
            options_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(options_backgroundLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(options_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(51, 51, 51)
                .addGroup(options_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(options_backgroundLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(174, 174, 174)
                        .addComponent(title)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(options_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, options_backgroundLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(50, 50, 50)
                        .addComponent(jButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, options_backgroundLayout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addGap(46, 46, 46))
        );
        options_backgroundLayout.setVerticalGroup(
            options_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(options_backgroundLayout.createSequentialGroup()
                .addGroup(options_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(options_backgroundLayout.createSequentialGroup()
                        .addGroup(options_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton5))
                        .addGap(26, 26, 26)
                        .addGroup(options_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton7)))
                    .addGroup(options_backgroundLayout.createSequentialGroup()
                        .addGroup(options_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(options_backgroundLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(options_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton3)))
                            .addGroup(options_backgroundLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(title)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(options_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton2))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        background.add(options_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1000, 100));

        traspareted_background.setBackground(new java.awt.Color(0, 0, 0,180));
        traspareted_background.setToolTipText("");

        javax.swing.GroupLayout traspareted_backgroundLayout = new javax.swing.GroupLayout(traspareted_background);
        traspareted_background.setLayout(traspareted_backgroundLayout);
        traspareted_backgroundLayout.setHorizontalGroup(
            traspareted_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        traspareted_backgroundLayout.setVerticalGroup(
            traspareted_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        background.add(traspareted_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 420));

        background_bibliotec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background/img-background-bliblioteca5.png"))); // NOI18N
        background.add(background_bibliotec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Buho;
    private javax.swing.JPanel background;
    private javax.swing.JLabel background_bibliotec;
    private javax.swing.JPanel buho_background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel options_background;
    private javax.swing.JLabel title;
    private javax.swing.JPanel traspareted_background;
    // End of variables declaration//GEN-END:variables
}
