/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.igu;

import com.logic.Book;
import com.persistence.Books;
import com.persistence.BooksLoan;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author eljot
 */
public class Home extends javax.swing.JFrame {
    
    protected ArrayList<Book> bibliotec = new ArrayList<>();
    protected ArrayList<Book> bibliotecLoan = new ArrayList<>();
    protected Books bookpersistence = new Books();
    protected BooksLoan bookloanPersistence = new BooksLoan();

    
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/icons/Buho-creado-luna.png")).getImage());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPbackground = new javax.swing.JPanel();
        JLbuho = new javax.swing.JLabel();
        JPbuho_background = new javax.swing.JPanel();
        JPoptions_background = new javax.swing.JPanel();
        JBcrud = new javax.swing.JButton();
        JBsave = new javax.swing.JButton();
        JBloans = new javax.swing.JButton();
        JBload = new javax.swing.JButton();
        JLtitle = new javax.swing.JLabel();
        JPtraspareted_background = new javax.swing.JPanel();
        JLbackground_bibliotec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setResizable(false);

        JPbackground.setBackground(new java.awt.Color(204, 255, 255));
        JPbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbuho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/Buho-creado-luna.png"))); // NOI18N
        JPbackground.add(JLbuho, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        JPbuho_background.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout JPbuho_backgroundLayout = new javax.swing.GroupLayout(JPbuho_background);
        JPbuho_background.setLayout(JPbuho_backgroundLayout);
        JPbuho_backgroundLayout.setHorizontalGroup(
            JPbuho_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        JPbuho_backgroundLayout.setVerticalGroup(
            JPbuho_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        JPbackground.add(JPbuho_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        JPoptions_background.setBackground(new java.awt.Color(0, 0, 0));

        JBcrud.setBackground(new java.awt.Color(245, 245, 245));
        JBcrud.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        JBcrud.setText("Modify and add books");
        JBcrud.setBorderPainted(false);
        JBcrud.setFocusPainted(false);
        JBcrud.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JBcrudMouseMoved(evt);
            }
        });
        JBcrud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBcrudMouseExited(evt);
            }
        });
        JBcrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcrudActionPerformed(evt);
            }
        });

        JBsave.setBackground(new java.awt.Color(245, 245, 245));
        JBsave.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        JBsave.setText("Save File");
        JBsave.setBorderPainted(false);
        JBsave.setFocusPainted(false);
        JBsave.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JBsaveMouseMoved(evt);
            }
        });
        JBsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBsaveMouseExited(evt);
            }
        });
        JBsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsaveActionPerformed(evt);
            }
        });

        JBloans.setBackground(new java.awt.Color(245, 245, 245));
        JBloans.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        JBloans.setText("Book loans");
        JBloans.setBorderPainted(false);
        JBloans.setFocusPainted(false);
        JBloans.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JBloansMouseMoved(evt);
            }
        });
        JBloans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBloansMouseExited(evt);
            }
        });
        JBloans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBloansActionPerformed(evt);
            }
        });

        JBload.setBackground(new java.awt.Color(245, 245, 245));
        JBload.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        JBload.setText("Load File");
        JBload.setBorderPainted(false);
        JBload.setFocusPainted(false);
        JBload.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JBloadMouseMoved(evt);
            }
        });
        JBload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBloadMouseExited(evt);
            }
        });
        JBload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBloadActionPerformed(evt);
            }
        });

        JLtitle.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        JLtitle.setForeground(new java.awt.Color(255, 255, 255));
        JLtitle.setText("Owl Library");

        javax.swing.GroupLayout JPoptions_backgroundLayout = new javax.swing.GroupLayout(JPoptions_background);
        JPoptions_background.setLayout(JPoptions_backgroundLayout);
        JPoptions_backgroundLayout.setHorizontalGroup(
            JPoptions_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPoptions_backgroundLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(JBcrud, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(JBloans, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(JLtitle)
                .addGap(50, 50, 50)
                .addComponent(JBload, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(JBsave, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        JPoptions_backgroundLayout.setVerticalGroup(
            JPoptions_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPoptions_backgroundLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(JPoptions_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBloans, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLtitle)
                    .addComponent(JBcrud, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBload, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBsave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        JPbackground.add(JPoptions_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1000, 100));

        JPtraspareted_background.setBackground(new java.awt.Color(0, 0, 0,180));
        JPtraspareted_background.setToolTipText("");

        javax.swing.GroupLayout JPtraspareted_backgroundLayout = new javax.swing.GroupLayout(JPtraspareted_background);
        JPtraspareted_background.setLayout(JPtraspareted_backgroundLayout);
        JPtraspareted_backgroundLayout.setHorizontalGroup(
            JPtraspareted_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        JPtraspareted_backgroundLayout.setVerticalGroup(
            JPtraspareted_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        JPbackground.add(JPtraspareted_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 420));

        JLbackground_bibliotec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background/img-background-bliblioteca5.png"))); // NOI18N
        JPbackground.add(JLbackground_bibliotec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setListbook(ArrayList books){
        this.bibliotec = books;
    }
    public ArrayList<Book> getListbook(){
        return bibliotec;
    }
    public void setListbookLoan(ArrayList books){
        this.bibliotecLoan = books;
    }
    
    public ArrayList<Book> getBibliotecLoan() {
    return bibliotecLoan;
    }
    
    private void JBcrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcrudActionPerformed
       BookCrud crud = new BookCrud(this);
       crud.setVisible(true);
       crud.setLocationRelativeTo(null);
       this.setVisible(false);
       System.out.println("sdsdsd");
       crud.setListbook(bibliotec);
       System.out.println("xd");
    }//GEN-LAST:event_JBcrudActionPerformed

    private void JBloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBloadActionPerformed
        bibliotecLoan = bookloanPersistence.downloadProductFile();
        bibliotec = bookpersistence.downloadProductFile();
        JOptionPane.showMessageDialog(null,"The book list has been loaded successfully.","Library System",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JBloadActionPerformed

    private void JBsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsaveActionPerformed
        // TODO add your handling code here:
        bookpersistence.uploadWriteFile(bibliotec);
        bookloanPersistence.uploadWriteFile(bibliotecLoan);
        JOptionPane.showMessageDialog(null,"The book list has been saved successfully.","Library System",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JBsaveActionPerformed

    private void JBloansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBloansActionPerformed
        // TODO add your handling code here:
        BookLoan pageLoan = new BookLoan(this); 
        pageLoan.setVisible(true);
        pageLoan.setLocationRelativeTo(null);
        this.setVisible(false);
        pageLoan.setListbook(bibliotec);
        pageLoan.setListbookLoan(bibliotecLoan);
        
    }//GEN-LAST:event_JBloansActionPerformed

    private void JBloansMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBloansMouseMoved
        // TODO add your handling code here:
        JBloans.setBackground(new java.awt.Color(54, 52, 52));
        JBloans.setForeground(new java.awt.Color(245, 245, 245)); 
    }//GEN-LAST:event_JBloansMouseMoved

    private void JBloansMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBloansMouseExited
        // TODO add your handling code here:
        JBloans.setBackground(new java.awt.Color(245, 245, 245)); 
        JBloans.setForeground(new java.awt.Color(28, 28, 28));    
    }//GEN-LAST:event_JBloansMouseExited

    private void JBcrudMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBcrudMouseMoved
        // TODO add your handling code here:
        JBcrud.setBackground(new java.awt.Color(54, 52, 52));
        JBcrud.setForeground(new java.awt.Color(245, 245, 245)); 
    }//GEN-LAST:event_JBcrudMouseMoved

    private void JBcrudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBcrudMouseExited
        // TODO add your handling code here:
        JBcrud.setBackground(new java.awt.Color(245, 245, 245)); 
        JBcrud.setForeground(new java.awt.Color(28, 28, 28));  
    }//GEN-LAST:event_JBcrudMouseExited

    private void JBloadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBloadMouseExited
        // TODO add your handling code here:
        JBload.setBackground(new java.awt.Color(245, 245, 245)); 
        JBload.setForeground(new java.awt.Color(28, 28, 28));  
    }//GEN-LAST:event_JBloadMouseExited

    private void JBloadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBloadMouseMoved
        // TODO add your handling code here:
        JBload.setBackground(new java.awt.Color(54, 52, 52));
        JBload.setForeground(new java.awt.Color(245, 245, 245)); 
    }//GEN-LAST:event_JBloadMouseMoved

    private void JBsaveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBsaveMouseMoved
        // TODO add your handling code here:
        JBsave.setBackground(new java.awt.Color(54, 52, 52));
        JBsave.setForeground(new java.awt.Color(245, 245, 245)); 
    }//GEN-LAST:event_JBsaveMouseMoved

    private void JBsaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBsaveMouseExited
        // TODO add your handling code here:
        JBsave.setBackground(new java.awt.Color(245, 245, 245)); 
        JBsave.setForeground(new java.awt.Color(28, 28, 28));  
    }//GEN-LAST:event_JBsaveMouseExited



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBcrud;
    private javax.swing.JButton JBload;
    private javax.swing.JButton JBloans;
    private javax.swing.JButton JBsave;
    private javax.swing.JLabel JLbackground_bibliotec;
    private javax.swing.JLabel JLbuho;
    private javax.swing.JLabel JLtitle;
    private javax.swing.JPanel JPbackground;
    private javax.swing.JPanel JPbuho_background;
    private javax.swing.JPanel JPoptions_background;
    private javax.swing.JPanel JPtraspareted_background;
    // End of variables declaration//GEN-END:variables
}
